export const data = [
  {
    id: 1,
    service_type: "страхування",
    name: "T-I Медична страховка 40000 USD 30 Franchize Euroins (40000 USD)",
    details: "Включено: медицина, вагітність (обмежено)",
    insurance_period: "2026-04-01",
    price: 3000,
  },
  {
    id: 2,
    service_type: "страхування",
    name: "T-II Медична страховка 50000 USD 50 Franchize Allianz (50000 USD)",
    details: "Включено: медицина, стоматологія",
    insurance_period: "2025-10-01",
    price: 3500,
  },
  {
    id: 3,
    service_type: "страхування",
    name: "T-III Медична страховка 30000 USD 20 Franchize AXA (30000 USD)",
    details: "Включено: медицина, спорт (обмежено)",
    insurance_period: "2026-04-01",
    price: 2500,
  },
  {
    id: 4,
    service_type: "страхування",
    name: "T-IV Медична страховка 60000 USD 100 Franchize Bupa (60000 USD)",
    details: "Включено: медицина, екстрена допомога",
    insurance_period: "2027-04-01",
    price: 4500,
  },
  {
    id: 5,
    service_type: "трансфер",
    name: "Трансфер з аеропорту до готелю (економ)",
    details: "Легковий автомобіль, до 3 осіб",
    insurance_period: null,
    price: 500,
  },
  {
    id: 6,
    service_type: "трансфер",
    name: "Трансфер з аеропорту до готелю (бізнес)",
    details: "Бізнес-клас, до 3 осіб",
    insurance_period: null,
    price: 1200,
  },
  {
    id: 7,
    service_type: "трансфер",
    name: "Трансфер з аеропорту до готелю (мікроавтобус)",
    details: "Мікроавтобус, до 8 осіб",
    insurance_period: null,
    price: 1800,
  },
];
